name: frontend
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  table_calendar: ^3.1.2
  flutter_svg: ^2.0.15
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

flutter_launcher_icons:
  android: true
  ios:
    remove_alpha_ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: '#ffffff'

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/icon.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/Logo/logo_TNMS.png
    - assets/splashScreenImage.png
